name: webpack-react-typescript
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    # 临时的docker容器
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: home-pages
          FOLDER: dist
          BUILD_SCRIPT: yarn && yarn build
